/**
 *
 * Copy from: https://github.com/solana-foundation/solana-com-breakpoint/blob/main/components/SponsorModal/constants-grid.ts
 * 1. replace GRID_SLUGS with copied data
 * 2. node ./check-sponsors-standalone.js
 * 3. if changes needed, click the edit icon (pencil, popup text: "Edit the file in your fork of this project") and make a pull request back into the main repository
 *
 * */

const GRID_SLUGS = {
  // Phantom: "Phantom",
  // BONK: "Bonk Rewards",
  Solflare: "Solflare",
  Syndica: "Syndica",
  Unlimit: "Unlimit",
  Kamino: "Kamino_Finance",
  Avail: "avail",
  DRPC: "drpc",
  Magna: "Magna",
  Jito: "Jito",
  Vybe: "Vybe_Network",
  Wormhole: "Wormhole",
  Allnodes: "allnodes",
  D3: "d3_inc",
  DMCC: "dubai_multi_commodities_centre_authority_dmcc",
  reown: "Reown",
  Arcium: "Arcium",
  Alchemy: "alchemy",
  Solstice: "solsticelabs_io",
  Yala: "yala",
  WalletConnect: "walletconnect_network",
  Sollpay: "sollpay",
  Orbitflare: "orbitflare",
  Backpack: "Backpack",
  Fluxbeam: "FluxBeam",
  RockawayX: "RockawayX",
  trojan: "Trojan",
  DoubleZero: "doublezero_xyz",
  Cudis: "Cudis",
  Shelby: "shelby",
  Sanctum: "Sanctum",
  Kast: "kast_xyz",
  metaplex: "Metaplex",
  Circle: "Circle",
  Valannia: "Valannia",
  Lume: "plume",
  Ledger: "Ledger",
  Moonwalk: "Moonwalk",
  Aurory: "Aurory",
  Streamflow: "Streamflow",
  Decal: "decal",
  Solayer: "Solayer",
  Zeus: "Zeus_Network",
  OpenSea: "opensea_io",
  "1inch": "1inch",
  Dawn: "dawninternet",
  Chainlink: "Chainlink",
  Geodnet: "GEODNET",
  Adrena: "adrena",
  Bybit: "Bybit",
  Raiku: "raiku",
  Firedancer: "Firedancer",
  Anza: "Anza",
  Triad: "triadfi_co",
  Xbit: "Taxbit",
  Jupiter: "Jupiter",
  Kraken: "Kraken",
  Reap: "reap",
  Coinbase: "Coinbase",
  "The Render Network": "Render_Network",
  "Solana Policy Institute": "solanapolicyinstitute",
  "The Graph": "The_Graph",
  "Peanut Trade": "peanut_trade",
  "Listing.help": "listing_help",
  "Flash Trade": "Flash_Trade",
  "Pyth Network": "Pyth_Network",
  "Easy Labs": "itseasy_co",
  "Galaxy Digital": "Galaxy_Digital",
  "sideshift.ai": "SideShift_AI",
  SNS: "Solana_Name_Service",
  DFDV: "defi_development_corp_",
  "Play Solana": "playsolana",
  "Reserve Protocol": "reserve_protocol",
  "Solana Floor": "solana_floor",
  "Pancake Swap": "pancakeswap",
  "Monke DAO": "MonkeDAO",
  DFG: "digital_finance_graoup",
  "Renaud Partners": "Renaud_Partners",
  "Exo Technologies": "exo_technologies",
  GDN: "globaldollar",
  Unipay: "unitas", //Unipay rebranded to Unitas
  "0XMatcha": "Matcha",
  "Solana Spaces": "solanaspaces",
  Seeker: "solanamobile",
  "Pudgy Penguins": "pudgy_penguins",
  Ryder: "ryder",
  "Crypto.com": "Cryptocom",
  Walrus: "walrus",
  "Asymmetric Research": "asymmetric_re",
  Expaam: "exponential_age_asset_management_expaam",
  OtterSec: "osec_io",
  Animoca: "Animoca_Brands",
  Altitude: null, // TBD
  Blockzero: null, //Can't yet confirm this one? Need offical URL
};
module.exports = GRID_SLUGS;
